# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  legiondeldiablo.com:
    site_hosts:
      - canonical: legiondeldiablo.com
        redirects:
          - www.legiondeldiablo.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: nfuller52@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
